backend:
  name: github
  repo: carlaprv/carla-portfolio-gatsby
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: 'bio'
    label: 'Bio information'
    folder: 'content/bio' # The path to the folder where the documents are stored
    path: '{{slug}}/index'
    create: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: ''
    public_folder: ''
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Bio (pt)', name: 'biopt', widget: 'markdown' }
      - { label: 'Bio (en)', name: 'bioen', widget: 'markdown' }
      - { label: 'Minibio (pt)', name: 'minibiopt', widget: 'markdown' }
      - { label: 'Minibio (en)', name: 'minibioen', widget: 'markdown' }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts' # The path to the folder where the documents are stored
    path: '{{year}}/{{slug}}/index'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Language', name: 'language', widget: 'select', options: ["en", "pt"]}
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: list, default: [''] }
      - { label: 'Hyperlink', name: 'hyperlink', widget: string}
      - { label: 'Categories', name: 'categories', widget: list, default: [''] }
      - { label: 'Draft', name: 'draft', widget: "boolean", default: false }
  - name: 'youtube'
    label: 'Youtube'
    label_singular: 'video'
    description: 'Registrar novos vídeos no youtube.'
    folder: 'content/youtube'
    path: '{{year}}/{{title}}/index'
    create: true
    slug: "{{year}}--{{title}}"
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string'}
      - { label: 'Channel', name: 'channel', widget: 'string'}
      - { label: 'Video ID', name: 'videoid', widget: 'string' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image'}
      - { label: 'Youtube link', name: 'link', widget: 'string'}
  - name: 'talks'
    label: 'Talks'
    label_singular: 'talk'
    description: 'Registrar participação em palestras/painéis.'
    folder: 'content/talks'
    path: '{{year}}/{{title}}/index'
    create: true
    slug: "{{year}}--{{title}}"
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image'}
      - { label: 'Event or Conference', name: 'eventname', widget: 'string' }
      - { label: 'Country', name: 'country', widget: 'string' , required: false}
      - { label: 'State', name: 'state', widget: 'string' , required: false}
      - { label: 'City', name: 'city', widget: 'string' , required: false}
      - { label: 'Slides link', name: 'slides', widget: 'string', required: false}
      - { label: 'Video Link', name: 'video', widget: 'string', required: false}
      - { label: 'Article Link', name: 'article', widget: 'string', required: false}
  - name: 'podcasts'
    label: 'Podcasts'
    label_singular: 'episode'
    description: 'Registrar participação em podcasts.'
    folder: 'content/podcasts'
    path: '{{year}}/{{title}}/index'
    create: true
    slug: "{{year}}--{{title}}"
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Podcast Name', name: 'podcastname', widget: 'string' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Episode link', name: 'slides', widget: 'string' }
  - name: 'upcomingevents'
    label: 'Upcoming Events'
    description: 'Registrar próximos eventos'
    label_singular: 'event'
    folder: 'content/events'
    path: '{{year}}/{{title}}/index'
    create: true
    slug: "{{year}}--{{title}}"
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Event Name/Community', name: 'eventname', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Event Subscription Link', name: 'eventlink', widget: 'string' , required: false }
      - { label: 'Is it an Online Event?', name: 'online', widget: "boolean", default: false }
  - name: 'midianews'
    label: 'Midia News'
    description: 'Registrar entrevistas e matérias na mídia'
    label_singular: 'news'
    folder: 'content/news'
    path: '{{year}}/{{title}}/index'
    create: true
    slug: "{{year}}--{{title}}"
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Revista/portal', name: 'midianame', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', time_format: True }
      - { label: 'Autor', name: 'author', widget: 'string' , required: false }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' , required: false }
      - { label: 'Logotipo', name: 'logo', widget: 'image' , required: false }